spring.application.name=auth-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.profiles.active=dev

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Malahat.2002
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OAUTH2
spring.security.oauth2.client.registration.google.client-id=710312830068-e86g6vjr6fdair2la7g53r1dahig7pm3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}

#force Spring to use localhost / gateway host
server.forward-headers-strategy=framework