spring.application.name=trade-service
server.port=8083

app.jwt.secret=${JWT_SECRET:263ccbebb6b753af6cbfc59af437dc46}
app.auth.base-url=http://localhost:8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/trade_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Malahat.2002}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Kafka switch (IMPORTANT) ---
app.kafka.enabled=false
# app.kafka.enabled=true

# --- Kafka connection ---
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=trade-service
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record

logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

# Topic names
app.kafka.topics.trade-created=trades.events

# Don't fail app if topic missing (useful in dev)
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.admin.fail-fast=false