spring.application.name=discovery-service

server.port=8761

# Eureka Server settings
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
