spring.application.name=order-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.profiles.active=dev

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=Malahat.2002
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka bootstrap server (local via Docker)
spring.kafka.bootstrap-servers=localhost:9092

# Producer (send JSON messages)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

app.kafka.topics.trade-created=trades.events

# add type headers so consumers can deserialize easily
spring.kafka.producer.properties.spring.json.add.type.headers=true