spring.application.name=order-service
server.port=8081

app.exchange.default=XLON
app.exchanges=XLON,XNAS,XTKS

app.jwt.secret=${JWT_SECRET:263ccbebb6b753af6cbfc59af437dc46}
app.auth.base-url=http://localhost:8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.profiles.active=dev

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Malahat.2002}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka bootstrap server (local via Docker)
spring.kafka.bootstrap-servers=localhost:9092

# Producer (send JSON messages)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

app.kafka.topics.trade-created=trades.events

# add type headers so consumers can deserialize easily
spring.kafka.producer.properties.spring.json.add.type.headers=true


# =========================
# LOGGING (BEST PRACTICE)
# =========================

# Turn on ANSI colors in console
spring.output.ansi.enabled=ALWAYS

# Default log level (keep INFO in prod)
logging.level.root=INFO

# Your code packages (change com.ab to your base package)
logging.level.com.ab=DEBUG

# Reduce noisy frameworks
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN

# Show short logger name, include correlationId from MDC if present
# Pattern includes:
# date | level | pid | thread | correlationId | logger | message
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} \
%clr(%-5level) \
%clr(${PID}){magenta} \
%clr([%t]){faint} \
%clr([corr=%X{correlationId:-}]){cyan} \
%clr(%logger{36}){blue} \
- %msg%n%wEx

# =========================
# OPTIONAL: FILE LOGGING
# =========================
logging.file.name=logs/tradehub.log

# Rolling policy (Spring Boot default Logback supports these)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=14